### ISSUE TITLE
Mention nvitop somewhere?

### ISSUE THREAD

**Issue by plutonium-239** [msminhas93/nviwatch#2]
Hi, thanks for the rust alternative to nvitop (as mentioned in your email). 

I would think that since this is heavily relying on users being familiar with nvitop as well as directly using it's design, it's only fair to mention nvitop in the readme!

Thanks, 
Samarth

**Comment by bonlime** [comment]
nvitop is not the only monitor, and all of them basically show the same exact stats. (usage/temp/processe)

**Comment by plutonium-239** [comment]
> nvitop is not the only monitor, and all of them basically show the same exact stats. (usage/temp/processe)

Hi, I got an email from the developer of this tool explicitly mentioning this as a rust/modernized version of `nvitop`, so I believe my point still stands.

**Comment by Junyi-99** [comment]
> > nvitop is not the only monitor, and all of them basically show the same exact stats. (usage/temp/processe)
> 
> Hi, I got an email from the developer of this tool explicitly mentioning this as a rust/modernized version of `nvitop`, so I believe my point still stands.

I received the same email

**Comment by msminhas93** [comment]
@plutonium-239, it doesn't require familiarity with nvitop. It is pretty common to reach out to users of similar tools to gather feedback and suggest your project. However I agree it's worth mentioning. Will update soon

**Comment by msminhas93** [comment]
Benchmarks added
